BEGIN TRANSACTION;
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO "auth_permission" VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO "auth_permission" VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO "auth_permission" VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO "auth_permission" VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO "auth_permission" VALUES(5,3,'add_permission','Can add permission');
INSERT INTO "auth_permission" VALUES(6,3,'change_permission','Can change permission');
INSERT INTO "auth_permission" VALUES(7,3,'delete_permission','Can delete permission');
INSERT INTO "auth_permission" VALUES(8,3,'view_permission','Can view permission');
INSERT INTO "auth_permission" VALUES(9,2,'add_group','Can add group');
INSERT INTO "auth_permission" VALUES(10,2,'change_group','Can change group');
INSERT INTO "auth_permission" VALUES(11,2,'delete_group','Can delete group');
INSERT INTO "auth_permission" VALUES(12,2,'view_group','Can view group');
INSERT INTO "auth_permission" VALUES(13,4,'add_user','Can add user');
INSERT INTO "auth_permission" VALUES(14,4,'change_user','Can change user');
INSERT INTO "auth_permission" VALUES(15,4,'delete_user','Can delete user');
INSERT INTO "auth_permission" VALUES(16,4,'view_user','Can view user');
INSERT INTO "auth_permission" VALUES(17,5,'add_contenttype','Can add content type');
INSERT INTO "auth_permission" VALUES(18,5,'change_contenttype','Can change content type');
INSERT INTO "auth_permission" VALUES(19,5,'delete_contenttype','Can delete content type');
INSERT INTO "auth_permission" VALUES(20,5,'view_contenttype','Can view content type');
INSERT INTO "auth_permission" VALUES(21,6,'add_session','Can add session');
INSERT INTO "auth_permission" VALUES(22,6,'change_session','Can change session');
INSERT INTO "auth_permission" VALUES(23,6,'delete_session','Can delete session');
INSERT INTO "auth_permission" VALUES(24,6,'view_session','Can view session');
INSERT INTO "auth_permission" VALUES(25,7,'add_amenity','Can add amenity');
INSERT INTO "auth_permission" VALUES(26,7,'change_amenity','Can change amenity');
INSERT INTO "auth_permission" VALUES(27,7,'delete_amenity','Can delete amenity');
INSERT INTO "auth_permission" VALUES(28,7,'view_amenity','Can view amenity');
INSERT INTO "auth_permission" VALUES(29,8,'add_brochureimage','Can add brochure image');
INSERT INTO "auth_permission" VALUES(30,8,'change_brochureimage','Can change brochure image');
INSERT INTO "auth_permission" VALUES(31,8,'delete_brochureimage','Can delete brochure image');
INSERT INTO "auth_permission" VALUES(32,8,'view_brochureimage','Can view brochure image');
INSERT INTO "auth_permission" VALUES(33,11,'add_flattype','Can add flat type');
INSERT INTO "auth_permission" VALUES(34,11,'change_flattype','Can change flat type');
INSERT INTO "auth_permission" VALUES(35,11,'delete_flattype','Can delete flat type');
INSERT INTO "auth_permission" VALUES(36,11,'view_flattype','Can view flat type');
INSERT INTO "auth_permission" VALUES(37,12,'add_lead','Can add lead');
INSERT INTO "auth_permission" VALUES(38,12,'change_lead','Can change lead');
INSERT INTO "auth_permission" VALUES(39,12,'delete_lead','Can delete lead');
INSERT INTO "auth_permission" VALUES(40,12,'view_lead','Can view lead');
INSERT INTO "auth_permission" VALUES(41,13,'add_popupad','Can add popup ad');
INSERT INTO "auth_permission" VALUES(42,13,'change_popupad','Can change popup ad');
INSERT INTO "auth_permission" VALUES(43,13,'delete_popupad','Can delete popup ad');
INSERT INTO "auth_permission" VALUES(44,13,'view_popupad','Can view popup ad');
INSERT INTO "auth_permission" VALUES(45,14,'add_projectinfo','Can add project info');
INSERT INTO "auth_permission" VALUES(46,14,'change_projectinfo','Can change project info');
INSERT INTO "auth_permission" VALUES(47,14,'delete_projectinfo','Can delete project info');
INSERT INTO "auth_permission" VALUES(48,14,'view_projectinfo','Can view project info');
INSERT INTO "auth_permission" VALUES(49,15,'add_review','Can add review');
INSERT INTO "auth_permission" VALUES(50,15,'change_review','Can change review');
INSERT INTO "auth_permission" VALUES(51,15,'delete_review','Can delete review');
INSERT INTO "auth_permission" VALUES(52,15,'view_review','Can view review');
INSERT INTO "auth_permission" VALUES(53,16,'add_sitevisitor','Can add site visitor');
INSERT INTO "auth_permission" VALUES(54,16,'change_sitevisitor','Can change site visitor');
INSERT INTO "auth_permission" VALUES(55,16,'delete_sitevisitor','Can delete site visitor');
INSERT INTO "auth_permission" VALUES(56,16,'view_sitevisitor','Can view site visitor');
INSERT INTO "auth_permission" VALUES(57,9,'add_buildingflat','Can add building flat');
INSERT INTO "auth_permission" VALUES(58,9,'change_buildingflat','Can change building flat');
INSERT INTO "auth_permission" VALUES(59,9,'delete_buildingflat','Can delete building flat');
INSERT INTO "auth_permission" VALUES(60,9,'view_buildingflat','Can view building flat');
INSERT INTO "auth_permission" VALUES(61,17,'add_villaplot','Can add villa plot');
INSERT INTO "auth_permission" VALUES(62,17,'change_villaplot','Can change villa plot');
INSERT INTO "auth_permission" VALUES(63,17,'delete_villaplot','Can delete villa plot');
INSERT INTO "auth_permission" VALUES(64,17,'view_villaplot','Can view villa plot');
INSERT INTO "auth_permission" VALUES(65,10,'add_chatbotqa','Can add Chatbot Q&A');
INSERT INTO "auth_permission" VALUES(66,10,'change_chatbotqa','Can change Chatbot Q&A');
INSERT INTO "auth_permission" VALUES(67,10,'delete_chatbotqa','Can delete Chatbot Q&A');
INSERT INTO "auth_permission" VALUES(68,10,'view_chatbotqa','Can view Chatbot Q&A');
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "core_amenity" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "icon" varchar(50) NOT NULL, "description" varchar(300) NOT NULL, "order" integer NOT NULL);
CREATE TABLE "core_brochureimage" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "image" varchar(100) NOT NULL, "order" integer NOT NULL, "caption" varchar(200) NOT NULL);
CREATE TABLE "core_buildingflat" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "tower" varchar(10) NOT NULL, "floor" integer NOT NULL, "flat_number" varchar(20) NOT NULL, "status" varchar(20) NOT NULL, "flat_type_id" bigint NOT NULL REFERENCES "core_flattype" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "core_chatbotqa" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "question" varchar(500) NOT NULL, "answer" text NOT NULL, "keywords" varchar(500) NOT NULL, "is_active" bool NOT NULL, "order" integer NOT NULL, "created_at" datetime NOT NULL);
CREATE TABLE "core_flattype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "bhk" decimal NOT NULL, "carpet_area" varchar(50) NOT NULL, "price" decimal NOT NULL, "price_per_sqft" decimal NOT NULL, "description" text NOT NULL, "is_available" bool NOT NULL, "order" integer NOT NULL, "buildup_area" varchar(50) NOT NULL, "super_buildup_area" varchar(50) NOT NULL, "terrace_area" varchar(50) NOT NULL);
CREATE TABLE "core_lead" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL, "phone" varchar(20) NOT NULL, "flat_preference" varchar(50) NOT NULL, "message" text NOT NULL, "source" varchar(50) NOT NULL, "created_at" datetime NOT NULL, "is_contacted" bool NOT NULL, "email" varchar(254) NOT NULL, "popup_ad_id" bigint NULL REFERENCES "core_popupad" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "core_popupad" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(200) NOT NULL, "image" varchar(100) NULL, "description" text NOT NULL, "flat_type" varchar(50) NOT NULL, "link" varchar(200) NOT NULL, "is_active" bool NOT NULL, "is_external" bool NOT NULL, "project_logo" varchar(100) NULL, "created_at" datetime NOT NULL, "end_date" date NULL, "start_date" date NULL, "order" integer NOT NULL);
CREATE TABLE "core_projectinfo" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL, "tagline" varchar(500) NOT NULL, "description" text NOT NULL, "address" text NOT NULL, "city" varchar(100) NOT NULL, "state" varchar(100) NOT NULL, "pincode" varchar(10) NOT NULL, "phone" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "website" varchar(200) NOT NULL, "map_embed_url" varchar(200) NOT NULL, "facebook" varchar(200) NOT NULL, "instagram" varchar(200) NOT NULL, "twitter" varchar(200) NOT NULL, "youtube" varchar(200) NOT NULL, "director_name" varchar(200) NOT NULL, "director_title" varchar(200) NOT NULL, "director_bio" text NOT NULL, "rera_number" varchar(100) NOT NULL, "total_units" integer NOT NULL, "total_floors" integer NOT NULL, "total_towers" integer NOT NULL, "project_area" varchar(100) NOT NULL, "possession_date" varchar(100) NOT NULL);
CREATE TABLE "core_review" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL, "rating" integer NOT NULL, "comment" text NOT NULL, "designation" varchar(100) NOT NULL, "is_approved" bool NOT NULL, "created_at" datetime NOT NULL);
CREATE TABLE "core_sitevisitor" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "ip_address" char(39) NOT NULL, "user_agent" text NOT NULL, "page_visited" varchar(500) NOT NULL, "visited_at" datetime NOT NULL);
CREATE TABLE "core_villaplot" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "villa_no" integer NOT NULL UNIQUE, "status" varchar(20) NOT NULL, "owner_name" varchar(200) NOT NULL, "sold_at" datetime NULL, "notes" text NOT NULL, "reserved_by" varchar(200) NOT NULL, "reserved_until" datetime NULL, "completion_pct" integer NOT NULL);
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
INSERT INTO "django_content_type" VALUES(1,'admin','logentry');
INSERT INTO "django_content_type" VALUES(2,'auth','group');
INSERT INTO "django_content_type" VALUES(3,'auth','permission');
INSERT INTO "django_content_type" VALUES(4,'auth','user');
INSERT INTO "django_content_type" VALUES(5,'contenttypes','contenttype');
INSERT INTO "django_content_type" VALUES(6,'sessions','session');
INSERT INTO "django_content_type" VALUES(7,'core','amenity');
INSERT INTO "django_content_type" VALUES(8,'core','brochureimage');
INSERT INTO "django_content_type" VALUES(9,'core','buildingflat');
INSERT INTO "django_content_type" VALUES(10,'core','chatbotqa');
INSERT INTO "django_content_type" VALUES(11,'core','flattype');
INSERT INTO "django_content_type" VALUES(12,'core','lead');
INSERT INTO "django_content_type" VALUES(13,'core','popupad');
INSERT INTO "django_content_type" VALUES(14,'core','projectinfo');
INSERT INTO "django_content_type" VALUES(15,'core','review');
INSERT INTO "django_content_type" VALUES(16,'core','sitevisitor');
INSERT INTO "django_content_type" VALUES(17,'core','villaplot');
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
INSERT INTO "django_migrations" VALUES(1,'contenttypes','0001_initial','2026-08-25 12:04:45.993804');
INSERT INTO "django_migrations" VALUES(2,'auth','0001_initial','2026-08-25 12:04:46.020869');
INSERT INTO "django_migrations" VALUES(3,'admin','0001_initial','2026-08-25 12:04:46.042968');
INSERT INTO "django_migrations" VALUES(4,'admin','0002_logentry_remove_auto_add','2026-08-25 12:04:46.074621');
INSERT INTO "django_migrations" VALUES(5,'admin','0003_logentry_add_action_flag_choices','2026-08-25 12:04:46.088614');
INSERT INTO "django_migrations" VALUES(6,'contenttypes','0002_remove_content_type_name','2026-08-25 12:04:46.120540');
INSERT INTO "django_migrations" VALUES(7,'auth','0002_alter_permission_name_max_length','2026-08-25 12:04:46.144597');
INSERT INTO "django_migrations" VALUES(8,'auth','0003_alter_user_email_max_length','2026-08-25 12:04:46.160974');
INSERT INTO "django_migrations" VALUES(9,'auth','0004_alter_user_username_opts','2026-08-25 12:04:46.171037');
INSERT INTO "django_migrations" VALUES(10,'auth','0005_alter_user_last_login_null','2026-08-25 12:04:46.189212');
INSERT INTO "django_migrations" VALUES(11,'auth','0006_require_contenttypes_0002','2026-08-25 12:04:46.193669');
INSERT INTO "django_migrations" VALUES(12,'auth','0007_alter_validators_add_error_messages','2026-08-25 12:04:46.205169');
INSERT INTO "django_migrations" VALUES(13,'auth','0008_alter_user_username_max_length','2026-08-25 12:04:46.223301');
INSERT INTO "django_migrations" VALUES(14,'auth','0009_alter_user_last_name_max_length','2026-08-25 12:04:46.238761');
INSERT INTO "django_migrations" VALUES(15,'auth','0010_alter_group_name_max_length','2026-08-25 12:04:46.257449');
INSERT INTO "django_migrations" VALUES(16,'auth','0011_update_proxy_permissions','2026-08-25 12:04:46.270487');
INSERT INTO "django_migrations" VALUES(17,'auth','0012_alter_user_first_name_max_length','2026-08-25 12:04:46.292236');
INSERT INTO "django_migrations" VALUES(18,'core','0001_initial','2026-08-25 12:04:46.327922');
INSERT INTO "django_migrations" VALUES(19,'core','0002_alter_lead_email','2026-08-25 12:04:46.342587');
INSERT INTO "django_migrations" VALUES(20,'core','0003_alter_flattype_bhk','2026-08-25 12:04:46.357091');
INSERT INTO "django_migrations" VALUES(21,'core','0004_villaplot','2026-08-25 12:04:46.365695');
INSERT INTO "django_migrations" VALUES(22,'core','0005_flattype_buildup_area_flattype_super_buildup_area_and_more','2026-08-25 12:04:46.390669');
INSERT INTO "django_migrations" VALUES(23,'core','0006_alter_flattype_buildup_area_and_more','2026-08-25 12:04:46.404177');
INSERT INTO "django_migrations" VALUES(24,'core','0007_villaplot_reserved_by_villaplot_reserved_until_and_more','2026-08-25 12:04:46.419973');
INSERT INTO "django_migrations" VALUES(25,'core','0008_alter_popupad_image','2026-08-25 12:04:46.431354');
INSERT INTO "django_migrations" VALUES(26,'core','0009_popupad_end_date_popupad_start_date','2026-08-25 12:04:46.441945');
INSERT INTO "django_migrations" VALUES(27,'core','0010_alter_popupad_options_popupad_order','2026-08-25 12:04:46.454573');
INSERT INTO "django_migrations" VALUES(28,'core','0011_lead_popup_ad','2026-08-25 12:04:46.468839');
INSERT INTO "django_migrations" VALUES(29,'core','0012_villaplot_completion_pct','2026-08-25 12:04:46.480681');
INSERT INTO "django_migrations" VALUES(30,'core','0013_chatbotqa','2026-08-25 12:04:46.489661');
INSERT INTO "django_migrations" VALUES(31,'core','0014_fix_amenity_icons','2026-08-25 12:04:46.515649');
INSERT INTO "django_migrations" VALUES(32,'sessions','0001_initial','2026-08-25 12:04:46.534756');
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE UNIQUE INDEX "core_buildingflat_tower_flat_number_df58674f_uniq" ON "core_buildingflat" ("tower", "flat_number");
CREATE INDEX "core_buildingflat_flat_type_id_7ced0578" ON "core_buildingflat" ("flat_type_id");
CREATE INDEX "core_lead_popup_ad_id_d4b359e1" ON "core_lead" ("popup_ad_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('django_migrations',32);
INSERT INTO "sqlite_sequence" VALUES('django_admin_log',0);
INSERT INTO "sqlite_sequence" VALUES('django_content_type',17);
INSERT INTO "sqlite_sequence" VALUES('auth_permission',68);
INSERT INTO "sqlite_sequence" VALUES('auth_group',0);
INSERT INTO "sqlite_sequence" VALUES('auth_user',0);
INSERT INTO "sqlite_sequence" VALUES('core_lead',0);
INSERT INTO "sqlite_sequence" VALUES('core_flattype',0);
INSERT INTO "sqlite_sequence" VALUES('core_popupad',0);
INSERT INTO "sqlite_sequence" VALUES('core_villaplot',0);
COMMIT;
