# Generated by Django 6.0.1 on 2026-06-28 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(default="star", max_length=50)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Amenities",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BrochureImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="brochure/")),
                ("order", models.IntegerField(default=0)),
                ("caption", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FlatType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("bhk", models.IntegerField(default=1)),
                ("carpet_area", models.CharField(default="", max_length=50)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "price_per_sqft",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("description", models.TextField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "bhk"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("flat_preference", models.CharField(blank=True, max_length=50)),
                ("message", models.TextField(blank=True)),
                ("source", models.CharField(default="website", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_contacted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PopupAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="popups/"),
                ),
                ("description", models.TextField(blank=True)),
                ("flat_type", models.CharField(blank=True, max_length=50)),
                ("link", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_external", models.BooleanField(default=False)),
                (
                    "project_logo",
                    models.ImageField(blank=True, null=True, upload_to="popups/logos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Silverwoods", max_length=200)),
                (
                    "tagline",
                    models.CharField(default="Luxury Living Redefined", max_length=500),
                ),
                ("description", models.TextField(default="")),
                ("address", models.TextField(default="")),
                ("city", models.CharField(default="", max_length=100)),
                ("state", models.CharField(default="", max_length=100)),
                ("pincode", models.CharField(default="", max_length=10)),
                ("phone", models.CharField(default="", max_length=20)),
                (
                    "email",
                    models.EmailField(default="info@silverwoods.com", max_length=254),
                ),
                ("website", models.URLField(blank=True)),
                ("map_embed_url", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("director_name", models.CharField(default="", max_length=200)),
                (
                    "director_title",
                    models.CharField(default="Managing Director", max_length=200),
                ),
                ("director_bio", models.TextField(default="")),
                ("rera_number", models.CharField(blank=True, max_length=100)),
                ("total_units", models.IntegerField(default=0)),
                ("total_floors", models.IntegerField(default=0)),
                ("total_towers", models.IntegerField(default=0)),
                ("project_area", models.CharField(blank=True, max_length=100)),
                ("possession_date", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name_plural": "Project Info",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("rating", models.IntegerField(default=5)),
                ("comment", models.TextField()),
                ("designation", models.CharField(blank=True, max_length=100)),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("page_visited", models.CharField(max_length=500)),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-visited_at"],
            },
        ),
        migrations.CreateModel(
            name="BuildingFlat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tower", models.CharField(default="A", max_length=10)),
                ("floor", models.IntegerField()),
                ("flat_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("reserved", "Reserved"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "flat_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.flattype"
                    ),
                ),
            ],
            options={
                "ordering": ["tower", "floor", "flat_number"],
                "unique_together": {("tower", "flat_number")},
            },
        ),
    ]
