# Generated by Django 6.0.1 on 2026-06-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_lead_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flattype",
            name="bhk",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
    ]
