# Generated by Django 6.0.1 on 2026-07-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_villaplot"),
    ]

    operations = [
        migrations.AddField(
            model_name="flattype",
            name="buildup_area",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="flattype",
            name="super_buildup_area",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="flattype",
            name="terrace_area",
            field=models.CharField(default="", max_length=50),
        ),
    ]
