# Generated by Django 6.0.1 on 2026-07-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_flattype_buildup_area_flattype_super_buildup_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flattype",
            name="buildup_area",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="flattype",
            name="carpet_area",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="flattype",
            name="super_buildup_area",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="flattype",
            name="terrace_area",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
