# Generated by Django 6.0.1 on 2026-07-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_flattype_buildup_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="villaplot",
            name="reserved_by",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="villaplot",
            name="reserved_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="villaplot",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("sold", "Sold"),
                    ("reserved", "Reserved"),
                    ("not_for_sale", "Not for Sale"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
