# Generated by Django 6.0.1 on 2026-07-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_villaplot_reserved_by_villaplot_reserved_until_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="popupad",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="popups/"),
        ),
    ]
