# Generated by Django 6.0.1 on 2026-07-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_popupad_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="popupad",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="popupad",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
