# Generated by Django 6.0.1 on 2026-07-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_popupad_end_date_popupad_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="popupad",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="popupad",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
