# Generated by Django 6.0.1 on 2026-07-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_popupad_options_popupad_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="popup_ad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="core.popupad",
            ),
        ),
    ]
