# Generated by Django 6.0.1 on 2026-07-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_lead_popup_ad"),
    ]

    operations = [
        migrations.AddField(
            model_name="villaplot",
            name="completion_pct",
            field=models.IntegerField(default=0),
        ),
    ]
