# Generated by Django 6.0.1 on 2026-07-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_villaplot_completion_pct"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                (
                    "keywords",
                    models.CharField(
                        help_text="Comma-separated keywords that trigger this question (e.g. price,cost,rate)",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chatbot Q&A",
                "verbose_name_plural": "Chatbot Q&As",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
